service: s3unzipper

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "arn:aws:s3:*"

stage: dev
region: us-east-1

functions:
  main:
    handler: handler.main
    environment:
      training_job_name: "vrp-oktank-logistics-2020-01-03-19-45-39-122"
